apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gds
namePrefix: gagan-

resources:
- Deployment.yaml
- Services.yaml

images:
- name: nginx
  newTag: 1.20.0

replicas:
- count: 4
  name: gagan-nginx-deployment
